# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

baseURL = "https://marcoribeiro.ml"
theme = "blowfish"
languageCode = "en"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

googleAnalytics = "G-47N24H4SZY"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
