languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Marco Ribeiro"
logo = "img/compass.png"
description = ""
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Marco Ribeiro"
  image = "img/marcoribeiro.jpg"
  bio = "Data engineer, developer and technology enthusiast"
  links = [
    { github = "https://github.com/elmarculino" },
    { linkedin = "https://www.linkedin.com/in/marco-antonio-soares-ribeiro/" },
    { twitter = "https://twitter.com/elmarculino" },
  ]
